environment:
  matrix:
    - NODEJS_VERSION: "4"
    - NODEJS_VERSION: "6"

matrix:
  fast_finish: true

skip_branch_with_pr: true

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  # Get the version of Node.js
  - ps: Install-Product node $Env:NODEJS_VERSION
  # install modules
  - npm install
  - node --version
  - npm --version

test_script:
  - npm run lint
  - npm run vscode:prepublish
  - npm test

# Don't actually build.
build: off

deploy: off
